name: Docker Image Build and Publish to Docker Hub

on:
  push:
    branches:
      - development  # Changer en la branche que vous souhaitez surveiller

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --file Dockerfile \
            --tag justtryon/papillonserver:latest \
            --platform linux/amd64,linux/aarch64 \
            .
      
      - name: Push Docker image to Docker Hub
        run: |
          docker buildx create --use
          docker buildx build \
            --file Dockerfile \
            --tag justtryon/papillonserver:latest \
            --platform linux/amd64,linux/aarch64 \
            --push .
